server:
  port: 1111
spring:
  application:
    name: rabbit-fanout-exchange
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    publisher-confirms: true
